### ISSUE TITLE
Application not response

### ISSUE THREAD

**Issue by MinChanSike** [inspiredtechnologies/IP-Camera-Emulator#1]
When video file is end, Application is not response, then crash.
It can configure video stream loop by time or forever?

**Comment by inspiredtechnologies** [comment]
The video stream should loop forever, however in my tests only the VLC libraries from version 2.2.6 and version 1.1.9 seem to work in this regard. Could you check are you already using either of those two versions?

**Comment by MinChanSike** [comment]
With VLC v2.2.6 and v1.1.9, application will not crash, but video playing is going to stop and need to start play it again. How about adding multiple video file? How you think, it will play smoothly?

**Comment by inspiredtechnologies** [comment]
Just need to find out in your case does the IP camera emulator app continue to indicate the channel is "streaming" under the Status column after video playback reached the end? If yes, could you review how are you playing/receiving the RTSP stream?

If you are using VLC player to receive & render the RTSP stream, try enable loop playback in VLC player - otherwise it's doesn't seem to be able to handle the transition and will stop playing. It's probably because the VLC library in the IP cam emulator tears down the RTSP stream at the end of the video clip and waits for the client to setup the connection sequence again. The other RTSP client I've testing is the Milestone XProtect universal driver which continues to receive the looped video stream without stopping,
